#!/usr/bin/env python3
"""Static rule scan for projects generated by android-app-builder.

Enforces the automatable part of references/rules/*.md that detekt/ktlint/lint do not
cover (or cover too loosely). Each finding carries the rule ID from the rule files.

Usage: check_rules.py <project-root> [--json] [--module feature/noteslist]
Exit 0 = no violations (warnings allowed), 1 = violations found.

Escape hatch: a line containing `rules-ignore: <RULE-ID> <reason>` (in a comment) skips that
rule on that line and the next one. The reason is mandatory and is reviewed in self-review.
"""
import argparse
import json
import os
import re
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict

SKIP_DIRS = {".git", ".gradle", "build", ".idea", ".kotlin", "intermediates", "node_modules"}
PREVIEW_ANN = re.compile(r"@(\w*Preview\w*)\b")
IGNORE = re.compile(r"rules-ignore:\s*([A-Z0-9_-]+)\s+\S+")

DEPRECATED = [
    (r"\bAsyncTask\b", "AsyncTask", "DEPR-01"), (r"\bAsyncTaskLoader\b", "AsyncTaskLoader", "DEPR-01"),
    (r"\bLoaderManager\b", "LoaderManager", "DEPR-01"), (r"android\.content\.Loader\b", "android.content.Loader", "DEPR-01"),
    (r"\bstartActivityForResult\b", "startActivityForResult", "DEPR-01"), (r"\bonActivityResult\b", "onActivityResult", "DEPR-01"),
    (r"PreferenceManager\.getDefaultSharedPreferences", "PreferenceManager.getDefaultSharedPreferences", "DEPR-02"),
    (r"\bHttpURLConnection\b", "HttpURLConnection", "DEPR-03"), (r"org\.apache\.http", "Apache HttpClient", "DEPR-03"),
    (r"\bListView\b", "ListView", "DEPR-03"), (r"\bWebViewFragment\b", "WebViewFragment", "DEPR-03"),
    (r"\bActionBarActivity\b", "ActionBarActivity", "DEPR-01"),
]
STALE_LIBS = [
    (r"io\.reactivex\.rxjava2:", "RxJava2"), (r"io\.reactivex:rxjava:", "RxJava1"),
    (r"com\.android\.support:", "support library"), (r"androidx\.legacy:legacy-support", "legacy-support"),
    (r"com\.squareup\.okhttp3:okhttp:3\.", "OkHttp 3"), (r"com\.squareup\.retrofit2:retrofit:2\.[0-8]\.", "Retrofit < 2.9"),
    (r"androidx\.security:security-crypto", "security-crypto (deprecated, use Tink)"),
]
RAW_M3 = re.compile(r"^import androidx\.compose\.material3\.(Button|OutlinedButton|TextButton|ElevatedButton|FilledTonalButton|"
                    r"FloatingActionButton|ExtendedFloatingActionButton|SmallFloatingActionButton|LargeFloatingActionButton|"
                    r"TopAppBar|CenterAlignedTopAppBar|MediumTopAppBar|LargeTopAppBar|Card|ElevatedCard|OutlinedCard|"
                    r"TextField|OutlinedTextField|NavigationBar|NavigationBarItem|AlertDialog)$")
SECRET = re.compile(r"""(?i)\b(api[_-]?key|secret|client[_-]?secret|access[_-]?token|password|passwd)\b\s*[:=]\s*["'][^"'$\s]{8,}["']""")
SECRET_TOKENS = re.compile(r"AIza[0-9A-Za-z_\-]{35}|sk_live_[0-9A-Za-z]{10,}|ghp_[0-9A-Za-z]{30,}|xox[baprs]-[0-9A-Za-z-]{10,}")

MAX_FILE_LINES = 300
HARD_FILE_LINES = 500
MIN_TEST_RATIO = 0.4
MIN_FEATURE_TEST_RATIO = 0.5


class Scanner:
    def __init__(self, root, module=None, final=False):
        self.root = os.path.abspath(root)
        self.module = module.strip("/") if module else None
        self.final = final
        self.findings = []

    # ------------------------------------------------------------ helpers
    def add(self, rule, severity, path, line, msg):
        self.findings.append({"rule": rule, "severity": severity, "file": os.path.relpath(path, self.root),
                              "line": line, "message": msg})

    def files(self, exts):
        base = os.path.join(self.root, self.module) if self.module else self.root
        for dp, dns, fns in os.walk(base):
            dns[:] = [d for d in dns if d not in SKIP_DIRS]
            for fn in fns:
                if os.path.splitext(fn)[1] in exts:
                    yield os.path.join(dp, fn)

    def rel(self, path):
        return os.path.relpath(path, self.root).replace(os.sep, "/")

    @staticmethod
    def read(path):
        with open(path, encoding="utf-8", errors="replace") as fh:
            return fh.read()

    @staticmethod
    def strip_comments_keep_lines(src):
        """Blank out comments and string contents? No: blank only comments, keep line count."""
        out, i, n = [], 0, len(src)
        in_str = False
        while i < n:
            c = src[i]
            if not in_str and src.startswith("//", i):
                j = src.find("\n", i)
                j = n if j == -1 else j
                out.append(" " * (j - i)); i = j; continue
            if not in_str and src.startswith("/*", i):
                j = src.find("*/", i + 2)
                j = n if j == -1 else j + 2
                out.append("".join(ch if ch == "\n" else " " for ch in src[i:j])); i = j; continue
            if c == '"' and (i == 0 or src[i - 1] != "\\"):
                in_str = not in_str
            out.append(c); i += 1
        return "".join(out)

    @staticmethod
    def preview_ranges(lines):
        """Line ranges (0-based, inclusive) of functions annotated with any *Preview* annotation."""
        ranges, i = [], 0
        while i < len(lines):
            if PREVIEW_ANN.search(lines[i]):
                depth, started, j = 0, False, i
                while j < len(lines):
                    depth += lines[j].count("{") - lines[j].count("}")
                    if "{" in lines[j]:
                        started = True
                    if started and depth <= 0:
                        break
                    j += 1
                ranges.append((i, j)); i = j + 1; continue
            i += 1
        return ranges

    @staticmethod
    def ignored(lines, idx, rule):
        for k in (idx, idx - 1):
            if 0 <= k < len(lines):
                m = IGNORE.search(lines[k])
                if m and m.group(1) == rule:
                    return True
        return False

    @staticmethod
    def is_preview_file(rel):
        name = os.path.basename(rel)
        return "/preview/" in rel or "Preview" in name or name.startswith("Fake") or "/testing/" in rel

    # ------------------------------------------------------------ kotlin sources
    def scan_kotlin(self):
        for path in self.files({".kt"}):
            rel = self.rel(path)
            is_test = "/src/test/" in rel or "/src/androidTest/" in rel
            raw = self.read(path)
            raw_lines = raw.split("\n")
            code = self.strip_comments_keep_lines(raw).split("\n")
            if is_test:
                self.scan_test_file(path, raw_lines)
                continue
            if "/src/main/" not in rel:
                continue
            in_ds = rel.startswith("core/designsystem/")
            in_feature = rel.startswith("feature/")
            previews = self.preview_ranges(raw_lines)
            in_preview = lambda i: any(a <= i <= b for a, b in previews) or self.is_preview_file(rel)
            interceptor = re.search(r":\s*(Interceptor|Authenticator)\b", raw) is not None
            di_file = "/di/" in rel

            n = len(raw_lines)
            if n > HARD_FILE_LINES:
                self.add("CORE-02", "violation", path, 1, "%d lines (> %d: audit god class)" % (n, HARD_FILE_LINES))
            elif n > MAX_FILE_LINES:
                self.add("CORE-02", "violation", path, 1, "%d lines (> %d) — split the file" % (n, MAX_FILE_LINES))

            for i, line in enumerate(code):
                ln = i + 1
                rl = raw_lines[i] if i < len(raw_lines) else ""

                def hit(rule, sev, msg):
                    if not self.ignored(raw_lines, i, rule):
                        self.add(rule, sev, path, ln, msg)

                if re.search(r"\b(TODO|FIXME|HACK)\b", rl):
                    hit("CORE-09", "violation", "TODO/FIXME/HACK left in code")
                if "!!" in re.sub(r'"[^"]*"', "", line):
                    hit("CORE-06", "violation", "'!!' operator")
                if re.search(r"@Suppress\(", line) and "justified:" not in rl and "rules-ignore" not in rl:
                    hit("CORE-10", "violation", "@Suppress without '// justified: <reason>'")
                if "GlobalScope" in line:
                    hit("CONC-02", "violation", "GlobalScope")
                if re.search(r"\brunBlocking\b", line) and not interceptor:
                    hit("CONC-03", "violation", "runBlocking outside an OkHttp Interceptor/Authenticator")
                if re.search(r"\bDispatchers\.(IO|Default|Unconfined)\b", line) and not di_file:
                    hit("CONC-01", "violation", "hard-coded Dispatcher — inject @IoDispatcher/@DefaultDispatcher")
                if re.search(r"\bprintln\(", line) or re.search(r"\bLog\.[vdiwe]\(", line) or "import android.util.Log" in line:
                    hit("SEC-06", "violation", "println/android.util.Log — use Timber (OBS-01)")
                if re.search(r"\bString\.format\(", line) and "Locale" not in line:
                    hit("I18N-10", "violation", "String.format without explicit Locale")
                if re.search(r'"\s*\.format\(', rl) and "Locale" not in rl:
                    hit("I18N-10", "violation", "String.format without explicit Locale")
                if "SimpleDateFormat(" in line:
                    hit("I18N-11", "violation", "SimpleDateFormat — use DateTimeFormatter.ofLocalized*")
                if "fallbackToDestructiveMigration" in line:
                    hit("DATA-04", "violation", "fallbackToDestructiveMigration wipes user data")
                if re.search(r'MessageDigest\.getInstance\(\s*"(MD5|SHA-?1)"', rl) or re.search(r'Cipher\.getInstance\(\s*"DES', rl):
                    hit("SEC-05", "violation", "insecure crypto (MD5/SHA1/DES)")
                if re.search(r"HostnameVerifier\s*\{\s*_\s*,\s*_\s*->\s*true", line) or "ALLOW_ALL_HOSTNAME_VERIFIER" in line:
                    hit("SEC-05", "violation", "trust-all hostname verifier")
                if re.search(r"checkServerTrusted\([^)]*\)\s*\{\s*\}", line):
                    hit("SEC-05", "violation", "trust-all X509TrustManager")
                if re.search(r"rawQuery\(\s*\"[^\"]*\"\s*\+", rl) or re.search(r"execSQL\(\s*\"[^\"]*\"\s*\+", rl):
                    hit("SEC-05", "violation", "SQL built by string concatenation")
                # An override of a library member the library deprecated must carry @Deprecated itself (Kotlin
                # warning otherwise) — that is not a project-own deprecated API.
                overrides_library = any("override " in nxt for nxt in raw_lines[i + 1:i + 4])
                if re.search(r"^\s*@Deprecated\b", line) and not overrides_library:
                    hit("DEPR-05", "violation", "project-own @Deprecated API left in code — migrate callers and delete it")
                for pat, name, rule in DEPRECATED:
                    if re.search(pat, line):
                        hit(rule, "violation", "deprecated API: %s" % name)
                if SECRET.search(rl) or SECRET_TOKENS.search(rl):
                    hit("SEC-01", "violation", "possible hard-coded secret")
                if re.search(r"catch\s*\([^)]*\)\s*\{\s*\}", line):
                    hit("ERR-02", "violation", "empty catch block")
                if re.search(r"catch\s*\(\s*\w+\s*:\s*(Exception|Throwable)\s*\)", line):
                    hit("ERR-05", "warning", "broad catch — narrow it and never swallow CancellationException")

                if not in_preview(i):
                    if re.search(r'\bText\(\s*"', rl) or re.search(r'\b(text|title|label|contentDescription|placeholder)\s*=\s*"[^"]*[A-Za-z]', rl):
                        hit("I18N-08", "violation", "hard-coded user-facing string — use stringResource(R.string.x) with R from core.i18n")
                    if re.search(r'Toast\.makeText\([^,]+,\s*"', rl):
                        hit("I18N-08", "violation", "hard-coded Toast text")
                    if not in_ds:
                        if re.search(r"\bColor\(\s*0x", line) or re.search(r"Color\.parseColor", line):
                            hit("RES-01", "violation", "hard-coded color outside core/designsystem — use theme tokens")
                        if re.search(r"(?<![\w.])(?!0\.dp)\d+(\.\d+)?\.(dp|sp)\b", line):
                            hit("RES-02", "violation", "hard-coded dp/sp outside core/designsystem — use <App>Theme.spacing / typography tokens")

                if re.search(r"\b(items|itemsIndexed)\(", line) and "key" not in " ".join(code[i:i + 3]) and "LazyPagingItems" not in line:
                    hit("COMP-05", "violation", "Lazy items() without stable key = { it.id }")

                if in_feature:
                    if RAW_M3.search(rl.strip()):
                        hit("DS-02", "violation", "raw Material 3 component in a feature — use the designsystem wrapper")
                    if re.search(r"^import .*\.(dto|network\.model)\.", rl.strip()) and "/data/" not in rel:
                        hit("ARCH-07", "violation", "feature imports network DTOs — use domain models")
                    if re.search(r"^import .*\.(network|database)\.", rl.strip()) and not re.search(r"\.(network|database)\.di\.", rl):
                        hit("ARCH-04", "violation", "feature talks to network/database directly — go through a repository")
                if in_ds and re.search(r"\.core\.i18n\.R\b", rl):
                    hit("DS-03", "violation", "designsystem must not use string resources — take text as a parameter")
                if rel.startswith("core/model/") and re.search(r"^import android\.", rl.strip()):
                    hit("ARCH-05", "violation", "Android type in :core:model")

            if in_ds and "/components/" in rel and "@Composable" in raw and not PREVIEW_ANN.search(raw):
                self.add("DS-06", "violation", path, 1, "designsystem component file without @Preview")

    def scan_test_file(self, path, lines):
        for i, line in enumerate(lines):
            if re.search(r"assertTrue\(\s*true\s*\)|assertEquals\(\s*1\s*,\s*1\s*\)", line):
                self.add("TEST-05", "violation", path, i + 1, "trivial assertion")
            if re.search(r"^\s*@Ignore\b", line):
                self.add("TEST-05", "violation", path, i + 1, "@Ignore'd test")

    # ------------------------------------------------------------ gradle / manifest / resources
    def scan_gradle(self):
        for path in self.files({".kts", ".gradle", ".toml"}):
            rel = self.rel(path)
            src = self.read(path)
            for i, line in enumerate(src.split("\n")):
                for pat, name in STALE_LIBS:
                    if re.search(pat, line):
                        self.add("BUILD-06", "violation", path, i + 1, "stale library: %s" % name)
                if re.search(r"""(storePassword|keyPassword)\s*=?\s*["'][^"'$]+["']""", line):
                    self.add("HARD-07", "violation", path, i + 1, "plaintext signing password — read from env/properties")
                if SECRET_TOKENS.search(line):
                    self.add("SEC-01", "violation", path, i + 1, "possible hard-coded secret")
                if re.search(r"\bbaseline\s*=", line) and "lint" in src:
                    self.add("BUILD-02", "violation", path, i + 1, "lint baseline configured — fix findings instead")
                if rel.startswith("feature/") and re.search(r"""projects\.feature\.|project\(\s*":feature:""", line):
                    self.add("ARCH-01", "violation", path, i + 1, "feature → feature dependency")
                if rel.startswith("core/designsystem/") and re.search(r"""projects\.core\.i18n|":core:i18n""", line):
                    self.add("DS-03", "violation", path, i + 1, "designsystem depends on :core:i18n")
        for path in self.files({".xml"}):
            if os.path.basename(path) == "lint-baseline.xml":
                self.add("BUILD-02", "violation", path, 1, "lint-baseline.xml present — never hide findings")

    def scan_manifests(self):
        for path in self.files({".xml"}):
            if os.path.basename(path) != "AndroidManifest.xml" or "/src/main/" not in self.rel(path):
                continue
            src = self.read(path)
            if re.search(r'usesCleartextTraffic\s*=\s*"true"', src):
                self.add("SEC-02", "violation", path, 1, "usesCleartextTraffic=true")
            if re.search(r'android:debuggable\s*=\s*"true"', src):
                self.add("SEC-04", "violation", path, 1, "android:debuggable=true in manifest")
            if re.search(r'allowBackup\s*=\s*"true"', src) and "dataExtractionRules" not in src:
                self.add("SEC-04", "violation", path, 1, "allowBackup=true without dataExtractionRules/fullBackupContent")

    def scan_strings(self):
        """i18n layout: all strings in core/i18n, per-feature files, prefixed keys, same files/keys per language."""
        i18n_res = os.path.join(self.root, "core", "i18n", "src", "main", "res")
        for path in self.files({".xml"}):
            rel = self.rel(path)
            if not re.search(r"/res/values[^/]*/[^/]+\.xml$", rel) or rel.startswith("core/i18n/"):
                continue
            if "/src/main/" not in rel:
                continue
            src = self.read(path)
            if re.search(r"<(string|plurals|string-array)\b", src):
                self.add("I18N-01", "violation", path, 1, "string resources outside :core:i18n")
        if self.module and not self.module.startswith("core/i18n"):
            return
        if not os.path.isdir(i18n_res):
            return
        folders = sorted(d for d in os.listdir(i18n_res) if d.startswith("values"))
        base = os.path.join(i18n_res, "values")
        if not os.path.isdir(base):
            return
        base_files = sorted(f for f in os.listdir(base) if f.startswith("strings_") and f.endswith(".xml"))
        base_keys = {}
        values_by_text = defaultdict(list)
        for f in base_files:
            prefix = f[len("strings_"):-len(".xml")] + "_"
            keys = self.xml_keys(os.path.join(base, f))
            base_keys[f] = set(keys)
            for k, text in keys.items():
                if not k.startswith(prefix):
                    self.add("I18N-03", "violation", os.path.join(base, f), 1, "key '%s' must start with '%s'" % (k, prefix))
                if text:
                    values_by_text[text.strip().lower()].append((f, k))
        for text, owners in values_by_text.items():
            files = {f for f, _ in owners}
            if len(files) > 1:
                self.add("I18N-05", "violation", base, 1, "duplicate text %r in %s — move to strings_common.xml"
                         % (text, ", ".join(sorted("%s:%s" % o for o in owners))))
        for folder in folders:
            if folder == "values" or not re.match(r"values-[a-z]{2}(-r[A-Z]{2})?$|values-b\+", folder):
                continue
            fdir = os.path.join(i18n_res, folder)
            have = sorted(f for f in os.listdir(fdir) if f.startswith("strings_") and f.endswith(".xml"))
            for f in base_files:
                if f not in have:
                    self.add("I18N-04", "violation", fdir, 1, "%s missing in %s" % (f, folder))
                    continue
                missing = base_keys[f] - set(self.xml_keys(os.path.join(fdir, f)))
                if missing:
                    self.add("I18N-04", "violation", os.path.join(fdir, f), 1, "missing translations: %s" % ", ".join(sorted(missing)))

    @staticmethod
    def xml_keys(path):
        try:
            root = ET.parse(path).getroot()
        except ET.ParseError:
            return {}
        out = {}
        for el in root:
            name = el.get("name")
            if el.get("translatable") == "false" or not name:
                continue
            out[name] = "".join(el.itertext()) if el.tag == "string" else ""
        return out

    def test_ratio(self):
        mods = defaultdict(lambda: [0, 0])
        for path in self.files({".kt"}):
            rel = self.rel(path)
            m = re.match(r"(.+?)/src/(main|test|androidTest)/", rel)
            if not m or rel.startswith("build-logic/"):
                continue
            mods[m.group(1)][0 if m.group(2) == "main" else 1] += 1
        total_main = sum(v[0] for v in mods.values())
        total_test = sum(v[1] for v in mods.values())
        ratio = (total_test / total_main) if total_main else 0.0
        for mod, (main, test) in sorted(mods.items()):
            if mod.startswith("feature/") and main and test / main < MIN_FEATURE_TEST_RATIO:
                self.add("TEST-02", "violation", os.path.join(self.root, mod), 1,
                         "feature test/source ratio %.2f (%d/%d) < %.1f — add screen/item/mapper tests"
                         % (test / main, test, main, MIN_FEATURE_TEST_RATIO))
            elif main >= 3 and test / main < MIN_TEST_RATIO and not mod.startswith(("core/model", "core/i18n", "core/testing")):
                self.add("TEST-02", "warning", os.path.join(self.root, mod), 1,
                         "test/source ratio %.2f (%d/%d) < %.1f" % (test / main, test, main, MIN_TEST_RATIO))
        if not self.module and total_main and ratio < MIN_TEST_RATIO:
            # The project total is enforced at handover (--final); during the build it grows feature by feature.
            self.add("TEST-02", "violation" if self.final else "warning", self.root, 1,
                     "project test/source ratio %.2f < %.1f" % (ratio, MIN_TEST_RATIO))
        return {"main_files": total_main, "test_files": total_test, "ratio": round(ratio, 2)}

    def run(self):
        self.scan_kotlin()
        self.scan_gradle()
        self.scan_manifests()
        self.scan_strings()
        ratio = self.test_ratio()
        violations = [f for f in self.findings if f["severity"] == "violation"]
        return {"violations": len(violations), "warnings": len(self.findings) - len(violations),
                "test_ratio": ratio, "findings": self.findings}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("--module", help="limit Kotlin/resource checks to one module path, e.g. feature/noteslist")
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--final", action="store_true", help="Stage E: enforce the project-wide test ratio")
    args = ap.parse_args()
    result = Scanner(args.root, args.module, args.final).run()
    if args.json:
        print(json.dumps(result, indent=1))
    else:
        for f in sorted(result["findings"], key=lambda f: (f["severity"] != "violation", f["file"], f["line"])):
            print("%-9s %-8s %s:%s  %s" % (f["severity"].upper(), f["rule"], f["file"], f["line"], f["message"]))
        print("check_rules: %d violation(s), %d warning(s), test ratio %.2f (%d/%d)"
              % (result["violations"], result["warnings"], result["test_ratio"]["ratio"],
                 result["test_ratio"]["test_files"], result["test_ratio"]["main_files"]))
    sys.exit(1 if result["violations"] else 0)


if __name__ == "__main__":
    main()
